/*
 * PostgREST API
 * This is a dynamic API generated by PostgREST
 *
 * OpenAPI spec version: 0.4.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package mad.apps.sabenza.data.model.employer

import com.google.gson.annotations.SerializedName
import io.swagger.annotations.ApiModelProperty

/**
 * Employers
 */
data class Employer(
        /**
         * Get firstName
         * @return firstName
         */
        @SerializedName("first_name")
        @get:ApiModelProperty(value = "")
        val firstName: String? = null,

        /**
         * Get lastName
         * @return lastName
         */
        @SerializedName("last_name")
        @get:ApiModelProperty(value = "")
        val lastName: String? = null,

        /**
         * Get email
         * @return email
         */
        @SerializedName("email")
        @get:ApiModelProperty(value = "")
        val email: String? = null,

        /**
         * Get aboutMe
         * @return aboutMe
         */
        @SerializedName("about_me")
        @get:ApiModelProperty(value = "")
        val aboutMe: String? = null,

        /**
         * Get phoneNumber
         * @return phoneNumber
         */
        @SerializedName("phone_number")
        @get:ApiModelProperty(value = "")
        val phoneNumber: String? = null,

        /**
         * Get aboutCompany
         * @return aboutCompany
         */
        @SerializedName("about_company")
        @get:ApiModelProperty(value = "")
        val aboutCompany: String? = null,

        /**
         * Get pictureId
         * @return pictureId
         */
        @SerializedName("picture_id")
        @get:ApiModelProperty(value = "")
        val pictureId: String? = null) {
    /**
     * Get id
     * @return id
     */
    @SerializedName("id")
    @get:ApiModelProperty(value = "")
    val id: Int? = null


    /**
     * Get mine
     * @return mine
     */
    @SerializedName("mine")
    @get:ApiModelProperty(value = "")
    val isMine: Boolean? = null

    /**
     * Get isPrivate
     * @return isPrivate
     */
    @SerializedName("is_private")
    @get:ApiModelProperty(value = "")
    val isIsPrivate: Boolean? = null

    /**
     * Get ratingAvg
     * @return ratingAvg
     */
    @SerializedName("rating_avg")
    @get:ApiModelProperty(value = "")
    val ratingAvg: String? = null

    /**
     * Get ratingSum
     * @return ratingSum
     */
    @SerializedName("rating_sum")
    @get:ApiModelProperty(value = "")
    val ratingSum: Int? = null

    /**
     * Get ratingCount
     * @return ratingCount
     */
    @SerializedName("rating_count")
    @get:ApiModelProperty(value = "")
    val ratingCount: Int? = null

}

