package mad.apps.sabenza.middleware

enum class MiddlewareError {
    UNKNOWN,

    FAILED_TO_REFRESH_ADDRESSES,

    FAILED_TO_REFRESH_EMPLOYEE,

    FAILED_TO_ADD_EMPLOYEE,

    FAILED_TO_LINK_SKILL_TO_EMPLOYEE,

    FAILED_TO_REFRESH_SKILLS,

    FAILED_TO_REFRESH_EMPLOYEE_SKILLS,

    FAILED_TO_ADD_OR_UPDATE_EMPLOYER,

    FAILED_TO_REFRESH_EMPLOYER
}