/*
 * PostgREST API
 * This is a dynamic API generated by PostgREST
 *
 * OpenAPI spec version: 0.4.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package mad.apps.sabenza.data.model.employee

import com.google.gson.annotations.SerializedName


class EmployeeSkill {
    @SerializedName("employee_id")
    var employeeId: Int? = null
    @SerializedName("skill_id")
    var skillId: String? = null
    @SerializedName("years_experience")
    var yearsExperience: String? = null

}

